-- Optional AI-generated compensation letter body (e.g. OpenAI from IMAP delay pipeline).

ALTER TABLE public.detected_refunds
  ADD COLUMN IF NOT EXISTS letter_text TEXT;

COMMENT ON COLUMN public.detected_refunds.letter_text IS 'Optional US English compensation letter generated by OpenAI when delay > threshold.';
